In [1]:
import osmnx as ox, networkx as nx, matplotlib.cm as cm, pandas as pd, numpy as np
pd.options.mode.chained_assignment = None
import matplotlib.pyplot as plt
import geopandas as gpd
import time
from math import sqrt
import pandas as pd
pd.set_option('precision', 10)
%matplotlib inline

In [2]:
import street_network_functions as snf
import utilities as uf

In [3]:
import shapely.geometry
from shapely.geometry import Point, LineString, Polygon, MultiPolygon, mapping, MultiLineString
from shapely.ops import nearest_points

In [4]:
city_name = 'London'
folder_ouptut ='Outputs/'+city_name+'/'
epsg = 27700
crs = {'init': 'epsg:27700', 'no_defs': True}

In [5]:
from importlib import reload
# reload(uf)

In [6]:
streets_gdf = gpd.read_file(folder_ouptut+city_name+'_paths.shp', driver='ESRI Shapefile')
polygon = gpd.read_file('C:/Users/g_filo01/sciebo/GIS Data/London/Congestion_area_polygon/Polygon.shp').to_crs(epsg=epsg)

In [253]:
trajectories1 = gpd.read_file('C:/Users/g_filo01/sciebo/GIS Data/Trajectories/GPSIES/track_points_1.shp').to_crs(epsg=epsg)
trajectories2 = gpd.read_file('C:/Users/g_filo01/sciebo/GIS Data/Trajectories/GPSIES/track_points_2.shp').to_crs(epsg=epsg)
trajectories3 = gpd.read_file('C:/Users/g_filo01/sciebo/GIS Data/Trajectories/GPSIES/track_points_3.shp').to_crs(epsg=epsg)

In [346]:
trajectories4 = gpd.read_file('C:/Users/g_filo01/sciebo/GIS Data/Trajectories/OSM/track_points_5.shp').to_crs(epsg=epsg)

In [254]:
area_to_clip = polygon.loc[0].geometry.buffer(200)

In [347]:
trajectories1 = trajectories1[trajectories1.geometry.within(area_to_clip)]
trajectories2 = trajectories2[trajectories2.geometry.within(area_to_clip)]
trajectories3 = trajectories3[trajectories3.geometry.within(area_to_clip)]
trajectories4 = trajectories4[trajectories4.geometry.within(area_to_clip)]

In [348]:
trajectories4['t'] = trajectories4['time'].str.slice(start = 11, stop=19)
trajectories4 = trajectories4.sort_values(['track_fid', 'track_se_1']).reset_index(drop = True)
trajectories4['seconds'] = ((trajectories4['t'].str.slice(start = 0, stop = 2).astype(int))*3600
                            + (trajectories4['t'].str.slice(start = 3, stop = 5).astype(int))*60
                            + (trajectories4['t'].str.slice(start = 6, stop = 8).astype(int)))
trajectories4.head()

,track_fid,track_seg_,track_se_1,time,type,geometry,t,seconds
0,18,0,0,2018/06/14 06:53:43.000,None,POINT Z (532998.1253076695 180162.966073447 -4...,06:53:43,24823
1,18,0,1,2018/06/14 06:53:44.000,None,POINT Z (532998.1253076695 180162.966073447 -4...,06:53:44,24824
2,18,0,2,2018/06/14 06:53:45.000,None,POINT Z (532998.1253076695 180162.966073447 -4...,06:53:45,24825
3,18,0,3,2018/06/14 06:53:46.000,None,POINT Z (532998.1253076695 180162.966073447 -4...,06:53:46,24826
4,18,0,4,2018/06/14 06:53:47.000,None,POINT Z (533003.7819064826 180161.2334580324 -...,06:53:47,24827

In [ ]:
trajectories4['speed'] = 0.0
previous_fid = None

index_fid = trajectories4.columns.get_loc("track_fid")+1
index_geometry = trajectories4.columns.get_loc("geometry")+1
index_seconds = trajectories4.columns.get_loc("seconds")+1

for row in trajectories4.itertuples():
   
    if previous_fid == None:
        trajectories4.set_value(row[0], 'speed', 1)
        previous_fid = row[index_fid]
        previous_index = row[0]
        continue
    
    if previous_fid != row[index_fid]:
        trajectories4.set_value(row[0], 'speed', 1)
        previous_fid = row[index_fid]
        previous_index = row[0]
        continue
        
    geo = row[index_geometry]
    previous_geometry = trajectories4.loc[previous_index].geometry
    if geo == previous_geometry:
        trajectories4.drop(row[0], axis = 0, inplace = True)
        continue
        
    distance = geo.distance(trajectories4.loc[previous_index].geometry)
    time_span = row[index_seconds] - trajectories4.loc[previous_index].seconds
    if time_span == 0: time_span = 0.01
    speed = float(distance)/float(time_span)
    previous_index = row[0]
    previous_fid = row[index_fid]
    trajectories4.set_value(row[0], 'speed', speed)

In [369]:
check = trajectories4.groupby(['track_fid'])['speed'].mean().reset_index(name = 'speed')
to_keep = check[check.speed > 1]
trajectories4_ped = trajectories4[trajectories4['track_fid'].isin(to_keep.track_fid.values.tolist())]
len(trajectories4_ped)

In [375]:
trajectories4_ped.head()

,track_fid,track_seg_,track_se_1,time,type,geometry,t,seconds,speed
0,18,0,0,2018/06/14 06:53:43.000,None,POINT Z (532998.1253076695 180162.966073447 -4...,06:53:43,24823,1.0000000000
4,18,0,4,2018/06/14 06:53:47.000,None,POINT Z (533003.7819064826 180161.2334580324 -...,06:53:47,24827,1.4790002178
12,18,0,12,2018/06/14 06:53:55.000,None,POINT Z (533005.1669745452 180161.3809764051 -...,06:53:55,24835,0.1741127153
13,18,0,13,2018/06/14 06:53:56.000,None,POINT Z (533004.79396633 180161.3044494962 -46...,06:53:56,24836,0.3807774894
14,18,0,14,2018/06/14 06:53:57.000,None,POINT Z (533006.2638219115 180159.2731204225 -...,06:53:57,24837,2.5073438608

In [381]:
trajectories4_ped.to_file('Outputs/tmp/'+city_name+'_pedestrians_trajOSM.shp', driver='ESRI Shapefile')

In [ ]:
f, ax = plt.subplots(1, figsize=(15, 15))
ax.set_axis_off()

trajectories1.plot(ax=ax, markersize = 0.75, color = 'springgreen', alpha=0.3)
trajectories2.plot(ax=ax, markersize = 0.75, color = 'springgreen', alpha=0.3)
trajectories3.plot(ax=ax, markersize = 0.75, color = 'springgreen', alpha=0.3)
trajectories4_ped.plot(ax=ax, markersize = 0.75, color = 'springgreen', alpha=0.3)
street_gdf.plot(ax=ax, linewidth = 1, color = 'grey')
plt.axis('equal')
plt.rcParams['figure.facecolor'] = 'black'

In [47]:
traj.trajID.unique().tolist()

['1-0',
 '1-1',
 '1-2',
 '1-3',
 '1-4',
 '1-7',
 '1-15',
 '1-16',
 '1-18',
 '1-20',
 '1-21',
 '1-22',
 '1-23',
 '1-24',
 '1-25',
 '1-26',
 '1-27',
 '1-29',
 '1-30',
 '1-31',
 '1-32',
 '1-33',
 '1-34',
 '1-35',
 '1-36',
 '1-37',
 '1-38',
 '1-39',
 '1-40',
 '1-41',
 '1-42',
 '1-43',
 '1-44',
 '1-45',
 '1-46',
 '1-47',
 '1-48',
 '1-50',
 '1-51',
 '1-52',
 '1-53',
 '1-55',
 '1-56',
 '1-58',
 '1-59',
 '1-61',
 '1-62',
 '1-64',
 '1-65',
 '1-66',
 '1-67',
 '1-68',
 '1-69',
 '1-70',
 '1-71',
 '1-74',
 '1-75',
 '1-76',
 '1-77',
 '1-78',
 '1-79',
 '1-91',
 '1-93',
 '1-94',
 '1-97',
 '1-98',
 '2-0',
 '2-1',
 '2-2',
 '2-6',
 '2-11',
 '2-12',
 '2-15',
 '2-17',
 '2-18',
 '2-22',
 '2-24',
 '2-27',
 '2-28',
 '2-29',
 '2-30',
 '2-31',
 '2-32',
 '2-33',
 '2-38',
 '2-43',
 '2-44',
 '2-46',
 '2-47',
 '2-48',
 '2-49',
 '2-50',
 '2-51',
 '2-53',
 '2-55',
 '2-56',
 '2-58',
 '2-59',
 '2-63',
 '2-64',
 '2-66',
 '2-67',
 '2-68',
 '2-69',
 '2-70',
 '2-73',
 '2-74',
 '2-75',
 '2-76',
 '2-77',
 '2-80',
 '2-81',
 '2-82',
 '2-83',
 '2-84',
 '2-85',
 '2-87',
 '2-88',
 '2-93',
 '2-94',
 '2-96',
 '2-97',
 '3-0',
 '3-1',
 '3-2',
 '3-3',
 '3-4',
 '3-7',
 '3-8',
 '3-10',
 '3-13',
 '3-14',
 '3-18',
 '3-20',
 '3-21',
 '3-22',
 '3-23',
 '3-27',
 '3-29',
 '3-32',
 '3-33',
 '4-18',
 '4-88',
 '4-96',
 '4-97',
 '4-98',
 '4-99',
 '4-100',
 '4-102',
 '4-103',
 '4-125',
 '4-126',
 '4-139',
 '4-140',
 '4-141',
 '4-142',
 '4-143',
 '4-144',
 '4-145',
 '4-147',
 '4-148',
 '4-149',
 '4-151',
 '4-152',
 '4-153',
 '4-154',
 '4-155',
 '4-156',
 '4-201',
 '4-217',
 '4-218',
 '4-219',
 '4-220',
 '4-221',
 '4-222',
 '4-223',
 '4-224',
 '4-225',
 '4-226',
 '4-227',
 '4-228',
 '4-229',
 '4-230',
 '4-231',
 '4-233',
 '4-234',
 '4-235',
 '4-236',
 '4-237',
 '4-242',
 '4-243',
 '4-244',
 '4-245',
 '4-246',
 '4-249',
 '4-250',
 '4-251',
 '4-253',
 '4-254',
 '4-255',
 '4-256',
 '4-257',
 '4-258',
 '4-259',
 '4-260',
 '4-261',
 '4-262',
 '4-264',
 '4-266',
 '4-267',
 '4-268',
 '4-281',
 '4-282',
 '4-283',
 '4-284',
 '4-303',
 '4-324',
 '4-428',
 '4-429',
 '4-493',
 '4-502',
 '4-512',
 '4-513',
 '4-516',
 '4-517',
 '4-518',
 '4-519',
 '4-521',
 '4-522',
 '4-523',
 '4-524',
 '4-525',
 '4-526',
 '4-527',
 '4-533',
 '4-534',
 '4-538',
 '4-539',
 '4-550',
 '4-569',
 '4-581',
 '4-584',
 '4-585',
 '4-651',
 '4-657',
 '4-658',
 '4-692',
 '4-702',
 '4-705',
 '4-728',
 '4-729',
 '4-730',
 '4-736',
 '4-738',
 '4-739',
 '4-740',
 '4-741',
 '4-742',
 '4-746',
 '4-747',
 '4-749',
 '4-750',
 '4-751',
 '4-770',
 '4-802',
 '4-974',
 '4-975',
 '4-976',
 '4-977',
 '4-980',
 '4-985',
 '4-986',
 '4-988',
 '4-989',
 '4-992',
 '4-993',
 '4-1000',
 '4-1001',
 '4-1002',
 '4-1005',
 '4-1007',
 '4-1016',
 '4-1018',
 '4-1019',
 '4-1026',
 '4-1034',
 '4-1036',
 '4-1042',
 '4-1053',
 '4-1055',
 '4-1061',
 '4-1062',
 '4-1067',
 '4-1068',
 '4-1077',
 '4-1079',
 '4-1080',
 '4-1081',
 '4-1085',
 '4-1086',
 '4-1090',
 '4-1095',
 '4-1097',
 '4-1100',
 '4-1103',
 '4-1107',
 '4-1108',
 '4-1111',
 '4-1112',
 '4-1114',
 '4-1115',
 '4-1116',
 '4-1117',
 '4-1118',
 '4-1131',
 '4-1132',
 '4-1135',
 '4-1142',
 '4-1146',
 '4-1157',
 '4-1163',
 '4-1165',
 '4-1171',
 '4-1178',
 '4-1182',
 '4-1183',
 '4-1189',
 '4-1192',
 '4-1200',
 '4-1202',
 '4-1205',
 '4-1240',
 '4-1241',
 '4-1250',
 '4-1279',
 '4-1289',
 '4-1292',
 '4-1354',
 '4-1355',
 '4-1356',
 '4-1359',
 '4-1361',
 '4-1369',
 '4-1373',
 '4-1374',
 '4-1379',
 '4-1384',
 '4-1387',
 '4-1388',
 '4-1389',
 '4-1397',
 '4-1414',
 '4-1415',
 '4-1418',
 '4-1419',
 '4-1422',
 '4-1424',
 '4-1429',
 '4-1430',
 '4-1432',
 '4-1434',
 '4-1436',
 '4-1437',
 '4-1439',
 '4-1441',
 '4-1443',
 '4-1445',
 '4-1450',
 '4-1469',
 '4-1471',
 '4-1473',
 '4-1474',
 '4-1475',
 '4-1476',
 '4-1477',
 '4-1478',
 '4-1479',
 '4-1480',
 '4-1481',
 '4-1482',
 '4-1483',
 '4-1484',
 '4-1485',
 '4-1486',
 '4-1487',
 '4-1488',
 '4-1489',
 '4-1490',
 '4-1491',
 '4-1492',
 '4-1493',
 '4-1494',
 '4-1495',
 '4-1496',
 '4-1497',
 '4-1498',
 '4-1499',
 '4-1507',
 '4-1508',
 '4-1509',
 '4-1510',
 '4-1511',
 '4-1512',
 '4-1513',
 '4-1514',
 '4-1515',
 '4-1516',
 '4-1517',
 '4-1518',
 '4-1519',
 '4-1520',
 '4-1521',
 '4-1522',
 '4-1523',
 '4-1524',
 '4-1525',
 '4-1526',
 '4-1527',
 '4-1528',
 '4-1529',
 '4-1530',
 '4-1531',
 '4-1532',
 '4-1533',
 '4-1534',
 '4-1535',
 '4-1536',
 '4-1537',
 '4-1538',
 '4-1541',
 '4-1542',
 '4-1543',
 '4-1555',
 '4-1556',
 '4-1566',
 '4-1567',
 '4-1569',
 '4-1572',
 '4-1573',
 '4-1576',
 '4-1577',
 '4-1583',
 '4-1584',
 '4-1597',
 '4-1598',
 '4-1600',
 '4-1605',
 '4-1606',
 '4-1615',
 '4-1616',
 '4-1621',
 '4-1624',
 '4-1625',
 '4-1627',
 '4-1637',
 '4-1638',
 '4-1639',
 '4-1642',
 '4-1658',
 '4-1668',
 '4-1670',
 '4-1671',
 '4-1674',
 '4-1675',
 '4-1678',
 '4-1679',
 '4-1680',
 '4-1694',
 '4-1696',
 '4-1702',
 '4-1703',
 '4-1706',
 '4-1707',
 '4-1711',
 '4-1712',
 '4-1713',
 '4-1715',
 '4-1719',
 '4-1720',
 '4-1721',
 '4-1726',
 '4-1729',
 '4-1730',
 '4-1731',
 '4-1739',
 '4-1740',
 '4-1741',
 '4-1742',
 '4-1743',
 '4-1745',
 '4-1746',
 '4-1749',
 '4-1752',
 '4-1757',
 '4-1760',
 '4-1761',
 '4-1762',
 '4-1773',
 '4-1779',
 '4-1786',
 '4-1802',
 '4-1803',
 '4-1805',
 '4-1806',
 '4-1808',
 '4-1810',
 '4-1813',
 '4-1816',
 '4-1820',
 '4-1821',
 '4-1822',
 '4-1823',
 '4-1825',
 '4-1832',
 '4-1838',
 '4-1843',
 '4-1848',
 '4-1852',
 '4-1854',
 '4-1855',
 '4-1857',
 '4-1869',
 '4-1874',
 '4-1875',
 '4-1879',
 '4-1881',
 '4-1882',
 '4-1886',
 '4-1900',
 '4-1901',
 '4-1903',
 '4-1904',
 '4-1905',
 '4-1908',
 '4-1922',
 '4-1923',
 '4-1926',
 '4-1927',
 '4-1930',
 '4-1933',
 '4-1943',
 '4-1949',
 '4-1950',
 '4-1952',
 '4-1956',
 '4-1957',
 '4-1959',
 '4-1969',
 '4-1970',
 '4-1972',
 '4-1973',
 '4-1974',
 '4-1975',
 '4-1978',
 '4-1980',
 '4-1982',
 '4-1983',
 '4-1986',
 '4-1987',
 '4-1990',
 '4-2000',
 '4-2011',
 '4-2012',
 '4-2014',
 '4-2022',
 '4-2032',
 '4-2042',
 '4-2043',
 '4-2053',
 '4-2055',
 '4-2060',
 '4-2063',
 '4-2065',
 '4-2067',
 '4-2069',
 '4-2070',
 '4-2079',
 '4-2081',
 '4-2084',
 '4-2087',
 '4-2088',
 '4-2090',
 '4-2094',
 '4-2095',
 '4-2099',
 '4-2102',
 '4-2103',
 '4-2104',
 '4-2105',
 '4-2114',
 '4-2115',
 '4-2116',
 '4-2119',
 '4-2120',
 '4-2126',
 '4-2130',
 '4-2132',
 '4-2133',
 '4-2136',
 '4-2137',
 '4-2138',
 '4-2142',
 '4-2144',
 '4-2154',
 '4-2157',
 '4-2159',
 '4-2162',
 '4-2164',
 '4-2166',
 '4-2169',
 '4-2170',
 '4-2172',
 '4-2175',
 '4-2177',
 '4-2179',
 '4-2185',
 '4-2191',
 '4-2195',
 '4-2196',
 '4-2197',
 '4-2201',
 '4-2202',
 '4-2205',
 '4-2206',
 '4-2208',
 '4-2209',
 '4-2215',
 '4-2218',
 '4-2219',
 '4-2220',
 '4-2224',
 '4-2225',
 '4-2226',
 '4-2235',
 '4-2236',
 '4-2237',
 '4-2241',
 '4-2245',
 '4-2246',
 '4-2247',
 '4-2248',
 '4-2249',
 '4-2252',
 '4-2254',
 '4-2255',
 '4-2324',
 '4-2325',
 '4-2326',
 '4-2441',
 '4-2454',
 '4-2455',
 '4-2484',
 '4-2502']

In [52]:
traj[traj.trajID == "1-0"].index.max()

287

In [56]:
index = traj.trajID.unique().tolist()
columns = ['length'] 
distances = pd.DataFrame(index=index, columns=columns)

In [65]:
for i in traj.trajID.unique().tolist():
    i_min = traj[traj.trajID == i].index.min()
    i_max = traj[traj.trajID == i].index.max()
    distance = traj.loc[i_min].geometry.distance(traj.loc[i_max].geometry)
    distances.set_value(i, 'length', distance)

In [68]:
distances.length.mean()

1555.0228822763677

In [377]:
trajectories1['trajID'] = '1-'+trajectories1.track_fid.astype(str)
trajectories2['trajID'] = '2-'+trajectories2.track_fid.astype(str)
trajectories3['trajID'] = '3-'+trajectories3.track_fid.astype(str)
trajectories4_ped['trajID'] = '4-'+trajectories4_ped.track_fid.astype(str)

In [379]:
traj = pd.concat([trajectories1, trajectories2, trajectories3])
traj = traj[['trajID', 'geometry']]
traj.head()

  trajID                                           geometry
0    1-0  POINT Z (531638.1245004772 181175.7136688835 -...
1    1-0  POINT Z (531638.009747383 181172.6394184963 -2...
2    1-0  POINT Z (531699.7909919732 181173.1273892745 -...
3    1-0  POINT Z (531792.0421538057 181149.9250928523 -...
4    1-0  POINT Z (531858.3041784283 181138.290634157 -1...

In [383]:
trajectories4_slim = trajectories4_ped[['trajID', 'geometry']]

In [384]:
traj = pd.concat([traj, trajectories4_slim])
traj.reset_index(inplace=True, drop = True)

In [407]:
traj.to_file('Outputs/tmp/'+city_name+'_points_traj.shp', driver = 'ESRI Shapefile')

In [8]:
traj = gpd.read_file('Outputs/tmp/'+city_name+'/'+city_name+'_points_traj.shp').to_crs(epsg=epsg)

In [19]:
traj.head()

  trajID  id_closest                                     geometry
0    1-0         345  POINT (531638.1245006039 181175.7136683861)
1    1-0         345  POINT (531638.0097475096 181172.6394179996)
2    1-0         344  POINT (531699.7909921003 181173.1273887765)
3    1-0         341  POINT (531792.0421539331 181149.9250923514)
4    1-0         340    POINT (531858.304178556 181138.290633656)

In [24]:
int(streets_gdf.loc[8261].natural_id)

2015

In [25]:
sindex = streets_gdf.sindex
traj['id_closest'] = 0
traj['naturalID'] = 0
index_geometry = traj.columns.get_loc("geometry")+1
index_geometry_l = streets_gdf.columns.get_loc("geometry")+1

for row in traj.itertuples():
    geo = row[index_geometry]
    geo_buff = geo.buffer(150)
    possible_matches_index = list(sindex.intersection(geo_buff.bounds))
    possible_matches = streets_gdf.iloc[possible_matches_index]
    precise_matches  = possible_matches[possible_matches.intersects(geo_buff)]
    if(len(precise_matches) == 0): 
        traj.drop(row[0], axis = 0, inplace = True)
        continue
    distances = [(rowC[0], rowC[index_geometry_l].distance(geo)) for rowC in precise_matches.itertuples()]
    index = min(distances, key = lambda item:item[1])[0]
    traj.set_value(row[0], 'id_closest', index)
    nID = int(streets_gdf.loc[index].natural_id)
    traj.set_value(row[0], 'naturalID', nID)

In [ ]:
traj['id_closest'] = 0
traj['naturalID'] = 0
index_naturalID = traj.columns.get_loc("naturalID")+1
index_id = traj.columns.get_loc("trajID")+1
previous_id = None

for row in trajID
    if (previous_id == None) | (previous_id != row[index_id]):
        prevous_id = row[index_id]
        natural_id = row[index_naturalID]
        dict_natural[natural_id] = 1
        
    if previuous_id == row[index_id]
        if natural_id == row[index_naturalID]:
            dictionary[natural_id] += 1
        if natural_id != row[index_naturalID]:    
            if row[index_naturalID] in dict_natural.keys():
                if # delete stuff before
            else dict_natural[row[index_naturalID]] = 1

In [34]:
minimum = 6
grouped = traj.groupby(['id_closest', 'trajID']).size().reset_index(name = 'counts')
grouped = grouped[grouped.counts > minimum]
grouped
values = grouped.groupby(['id_closest']).size().reset_index(name = 'counts')
values.head()

   id_closest  counts
0           0      31
1           3       1
2           6       1
3           7       2
4           8       1

In [35]:
streets_gdf = pd.merge(streets_gdf, values[['id_closest','counts']], how= 'left', left_index = True, right_on = "id_closest")
streets_gdf.reset_index(drop = True, inplace = True)

In [12]:
streets_gdf['counts'].fillna(0, inplace = True)
streets_gdf.drop('id_closest', axis = 1, inplace = True)
streets_gdf.head()

,streetID,length,highway,name,v,u,key,Eb,Erw,Ab,natural_id,length_sc,geometry,counts
0,27,61.9609935961,unclassified,York Gate,13539,12971,0,1434.0,74249.1948533131,12302.0,5757,0.1245263601,LINESTRING (528256.7304999996 182141.096400000...,31.0
1,30,43.0651889559,trunk,Marylebone Road,13515,11,0,1126328.0,532870.3345246799,2358545.0,6367,0.0864537589,LINESTRING (528303.8957000002 182074.120400000...,0.0
2,31,39.8456146227,unclassified,York Gate,1012,11,0,12727.0,493457.0319978174,667513.0,8646,0.0799667332,LINESTRING (528303.8957000002 182074.120400000...,0.0
3,32,61.5192282462,trunk,Marylebone Road,432,11,0,1153328.0,526718.5420527948,2995426.0,6367,0.1236362601,LINESTRING (528303.8957000002 182074.120400000...,1.0
4,119,17.8318237145,primary,Portland Place,11697,43,0,287730.0,273572.8944622917,457488.0,1674,0.0356117931,LINESTRING (528704.1456000004 182068.777100000...,0.0

In [13]:
len(traj.trajID.unique())

653

In [14]:
streets_gdf['rel_count'] = streets_gdf['counts']/len(traj.trajID.unique())*100
streets_gdf.head()

,streetID,length,highway,name,v,u,key,Eb,Erw,Ab,natural_id,length_sc,geometry,counts,rel_count
0,27,61.9609935961,unclassified,York Gate,13539,12971,0,1434.0,74249.1948533131,12302.0,5757,0.1245263601,LINESTRING (528256.7304999996 182141.096400000...,31.0,4.7473200613
1,30,43.0651889559,trunk,Marylebone Road,13515,11,0,1126328.0,532870.3345246799,2358545.0,6367,0.0864537589,LINESTRING (528303.8957000002 182074.120400000...,0.0,0.0000000000
2,31,39.8456146227,unclassified,York Gate,1012,11,0,12727.0,493457.0319978174,667513.0,8646,0.0799667332,LINESTRING (528303.8957000002 182074.120400000...,0.0,0.0000000000
3,32,61.5192282462,trunk,Marylebone Road,432,11,0,1153328.0,526718.5420527948,2995426.0,6367,0.1236362601,LINESTRING (528303.8957000002 182074.120400000...,1.0,0.1531393568
4,119,17.8318237145,primary,Portland Place,11697,43,0,287730.0,273572.8944622917,457488.0,1674,0.0356117931,LINESTRING (528704.1456000004 182068.777100000...,0.0,0.0000000000

In [36]:
uf.plot_lines(streets_gdf, classes = 7, lw = 1, column = 'counts', title = 'title', legend = True, scheme = 'fisher_jenks', cmap = 'Greys_r')

KeyError: 'counts'

In [17]:
streets_gdf.to_file('Outputs/tmp/'+city_name+'/'+city_name+'_counts_od.shp', driver='ESRI Shapefile')